# --- COMPILATION (Builder) ---
FROM gcc:13.2 AS builder

SHELL ["/bin/bash", "-c"]

WORKDIR /app

COPY . .

RUN make

# --- RUNTIME ---
FROM debian:bullseye-slim

SHELL ["/bin/bash", "-c"]

WORKDIR /app

COPY --from=builder /app/compiled-app .

CMD ["./compiled-app"]